[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

# Environment variables for production
[context.production.environment]
  VITE_EMAILJS_PUBLIC_KEY = "${VITE_EMAILJS_PUBLIC_KEY}"
  VITE_EMAILJS_SERVICE_ID = "${VITE_EMAILJS_SERVICE_ID}"
  VITE_EMAILJS_TEMPLATE_ID = "${VITE_EMAILJS_TEMPLATE_ID}"

# SPA redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
