[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  VITE_EMAILJS_PUBLIC_KEY = "${VITE_EMAILJS_PUBLIC_KEY}"
  VITE_EMAILJS_SERVICE_ID = "${VITE_EMAILJS_SERVICE_ID}"
  VITE_EMAILJS_TEMPLATE_ID = "${VITE_EMAILJS_TEMPLATE_ID}"

# Configure secret scanning to ignore specific files and directories
[secrets]
  scan = { enabled = false }  # Disable secret scanning for now

# SPA redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
